import Vue from 'vue'
import Router from 'vue-router'

import Index from '../views/index'
import Layout from '../views/Layout/Layout'
import Login from '../views/login/index'

import SearchMap from'@/views/ConditionMonitoring/SearchMap/SearchMap'

Vue.use(Router)

export default new Router({
  mode: 'hash',
  routes: [
    {
      path: '/login',
      component: Login,
      hidden: true,
      meta: {auth: false}
    },
    {
      path: '/',
      redirect: '/login',
      component: Login,
      meta: {auth: false}
    },
    {
      path: '',
      name: 'Layout',
      component: Layout,
      meta: {auth: true},
      hidden: true,
      children: [{
        path: '/index',
        name: 'Index',
        // component: Index,
        component: () => import('../views/index'),
        meta: {title: '首页'},
      },
        // 状态监控
        { path: '/TodayData',
          name: 'TodayData',
          // component: TodayData,
          component: () => import('@/views/ConditionMonitoring/TodayData/TodayData'),
          meta: {title: '今日数据'}},
        { path: '/SearchMap',
          name: 'SearchMap',
          component: SearchMap,
          // component: () => import('@/views/ConditionMonitoring/SearchMap/SearchMap'),
          meta: {title: '地图查看'}},
        { path: '/EquipmentStatus',
          name: 'EquipmentStatus',
          // component: EquipmentStatus,
          component: () => import('@/views/ConditionMonitoring/EquipmentStatus/EquipmentStatus'),
          meta: {title: '设备状态'}},
        { path: '/IllegallyParkedCars',
          name: 'IllegallyParkedCars',
          // component: IllegallyParkedCars,
          component: () => import('@/views/ConditionMonitoring/IllegallyParkedCars/IllegallyParkedCars'),
          meta: {title: '违停车辆'}},
        { path: '/MessagePush',
          name: 'MessagePush',
          // component: MessagePush,
          component: () => import('@/views/ConditionMonitoring/MessagePush/MessagePush'),
          meta: {title: '消息推送'}},
        //路内业务
        //  停车记录
        { path: '/ParkingCar',
          // component: ParkingCar,
          component: () => import('@/views/ParkingInRoad/ParkingRecord/ParkingCar/ParkingCar'),
          name: 'ParkingCar',
          meta: {title: '在停车辆'}},
        { path: '/LonglyCar',
          // component: LonglyCar,
          component: () => import('@/views/ParkingInRoad/ParkingRecord/LonglyCar/LonglyCar'),
          name: 'LonglyCar',
          meta: {title: '超长停车'}},
        { path: '/LeavedCar',
          // component: LeavedCar,
          component: () => import('@/views/ParkingInRoad/ParkingRecord/LeavedCar/LeavedCar'),
          name: 'LeavedCar',
          meta: {title: '已离场车辆'}},
        //  收费管理
        { path: '/CurrentOrders',
          // component: CurrentOrders,
          component: () => import('@/views/ParkingInRoad/TollManage/CurrentOrders/CurrentOrders'),
          name: 'CurrentOrders',
          meta: {title: '当前订单'}},
        { path: '/TopArrears',
          component: () => import('@/views/ParkingInRoad/TollManage/TopArrears/TopArrears'),
          // component: TopArrears,
          name: 'TopArrears',
          meta: {title: '欠费排行'}},
        { path: '/HistoryOrders',
          // component: HistoryOrders,
          component: () => import('@/views/ParkingInRoad/TollManage/HistoryOrders/HistoryOrders'),
          name: 'HistoryOrders',
          meta: {title: '历史订单'}},
        { path: '/AbnormalOrders',
          // component: AbnormalOrders,
          component: () => import('@/views/ParkingInRoad/TollManage/AbnormalOrders/AbnormalOrders'),
          name: 'AbnormalOrders',
          meta: {title: '异常订单'}},
        //  投诉处理
        { path: '/CurrentComplain',
          // component: CurrentComplain,
          component: () => import('@/views/ParkingInRoad/ComplainManage/CurrentComplain/CurrentComplain'),
          name: 'CurrentComplain',
          meta: {title: '当前投诉'}},
        { path: '/ProcessedComplain',
          // component: ProcessedComplain,
          component: () => import('@/views/ParkingInRoad/ComplainManage/ProcessedComplain/ProcessedComplain'),
          name: 'ProcessedComplain',
          meta: {title: '已处理投诉'}},
        //  特殊车管理
        { path: '/WhiteListCars',
          // component: WhiteListCars,
          name: 'WhiteListCars',
          component: () => import('@/views/ParkingInRoad/SpecailCars/WhiteListCars/WhiteListCars'),
          meta: {title: '白名单'}},
        { path: '/BlackListCars',
          // component: BlackListCars,
          component: () => import('@/views/ParkingInRoad/SpecailCars/BlackListCars/BlackListCars'),
          name: 'BlackListCars',
          meta: {title: '黑名单'}},
        { path: '/DisabledCars',
          // component: DisabledCars,
          component: () => import('@/views/ParkingInRoad/SpecailCars/DisabledCars/DisabledCars'),
          name: 'DisabledCars',
          meta: {title: '残疾人车'}},
        { path: '/DiscountCars',
          // component: DiscountCars,
          component: () => import('@/views/ParkingInRoad/SpecailCars/DiscountCars/DiscountCars'),
          name: 'DiscountCars',
          meta: {title: '折扣车辆'}},
        //  停车卡管理
        { path: '/cardTypeManagement',
          // component: cardTypeManagement,
          name: 'cardTypeManagement',
          component: () => import('@/views/ParkingInRoad/ParkingCard/cardTypeManagement/cardTypeManagement'),
          meta: {title: '卡类型管理'}},
        { path: '/cardIssuingManagement',
          // component: cardIssuingManagement,
          name: 'cardIssuingManagement',
          component: () => import('@/views/ParkingInRoad/ParkingCard/cardIssuingManagement/cardIssuingManagement'),
          meta: {title: '发卡管理'}},
        { path: '/VehicleParkingCard',
          // component: VehicleParkingCard,
          name: 'VehicleParkingCard',
          component: () => import('@/views/ParkingInRoad/ParkingCard/VehicleParkingCard/VehicleParkingCard'),
          meta: {title: '车辆停车卡'}},
        // 收费规则
        { path: '/AddApproved',
          // component: AddApproved,
          component: () => import('@/views/ParkingInRoad/ChargeRule/AddApproved/AddApproved'),
          name: 'AddApproved',
          meta: {title: '添加规则'}},
        { path: '/UnApproved',
          // component: UnApproved,
          component: () => import('@/views/ParkingInRoad/ChargeRule/UnApproved/UnApproved'),
          name: 'UnApproved',
          meta: {title: '审核规则'}},
        { path: '/Approved',
          // component: Approved,
          component: () => import('@/views/ParkingInRoad/ChargeRule/Approved/Approved'),
          name: 'Approved',
          meta: {title: '已审核规则'}},
        // 发票管理
        {path: '/InvoiceByAPP',
          // component: InvoiceByAPP,
          component: () => import('@/views/ParkingInRoad/InvoiceManage/InvoiceByAPP/InvoiceByAPP'),
          name: 'InvoiceByAPP',
          meta: {title: 'APP开票'}},
        {path: '/InvoiceByPDA',
          // component: InvoiceByPDA,
          component: () => import('@/views/ParkingInRoad/InvoiceManage/InvoiceByPDA/InvoiceByPDA'),
          name: 'InvoiceByPDA',
          meta: {title: 'PDA发票'}},
        {path: '/BillAllocation',
          // component: BillAllocation,
          component: () => import('@/views/ParkingInRoad/InvoiceManage/BillAllocation/BillAllocation'),
          name: 'BillAllocation',
          meta: {title: '票据配置'}},
        //员工管理
        { path: '/Staff',
          name: 'Staff',
          // component: Staff,
          component: () => import('../views/StaffManage/Staff/Staff'),
          meta: {title: '员工列表'}},
        //  考勤查询
        { path: '/Personnel',
          name: 'Personnel',
          // component: Personnel,
          component: () => import('../views/StaffManage/Attendance/Personnel/Personnel'),
          meta: {title: '人员维度'}},
        { path: '/DailyAttendance',
          name: 'DailyAttendance',
          // component: DailyAttendance,
          component: () => import('../views/StaffManage/Attendance/DailyAttendance/DailyAttendance'),
          meta: {title: '每日出勤'}},
        //分析报表
        { path: '/OperationsAnalysis',
          name: 'OperationsAnalysis',
          component: () => import('../views/AnalysisReports/OperationsAnalysis/OperationsAnalysis'),
          meta: {title: '运营分析'}},
        { path: '/MonthlyFinancialReports',
          name: 'MonthlyFinancialReports',
          // component: MonthlyFinancialReports,
          component: () => import('../views/AnalysisReports/BasicReports/MonthlyFinancialReports/MonthlyFinancialReports'),
          meta: {title: '月收入统计'}},
        { path: '/PayReports',
          name: 'PayReports',
          component: () => import('../views/AnalysisReports/BasicReports/PayReports/PayReports'),
          meta: {title: '收费员统计'}},
          { path: '/financialReport',
          name: 'financialReport',
          component: () => import('../views/AnalysisReports/BasicReports/financialReport/financialReport'),
          meta: {title: '财务报表'}},
        { path: '/arrearage',
          name: 'arrearage',
          component: () => import('../views/AnalysisReports/BasicReports/arrearage/arrearage'),
          meta: {title: '欠费统计'}},
          { path: '/channelStatistics',
          name: 'channelStatistics',
          component: () => import('../views/AnalysisReports/BasicReports/channelStatistics'),
          meta: {title: '渠道对账'}},
        { path: '/OperateLog',
          name: 'OperateLog',
          // component: OperateLog,
          component: () => import('../views/AnalysisReports/LogManage/OperateLog/OperateLog'),
          meta: {title: '操作日志'}},
        //会员维护
        { path: '/PersonalVip',
          name: 'PersonalVip',
          // component: PersonalVip,
          component: () => import('../views/VipMaintain/PersonalVip/PersonalVip'),
          meta: {title: '个人会员'}},
        { path: '/CompanyVip',
          name: 'CompanyVip',
          // component: CompanyVip,
          component: () => import('../views/VipMaintain/CompanyVip/CompanyVip'),
          meta: {title: '单位会员'}},
        { path: '/RetrieveCar',
          name: 'RetrieveCar',
          // component: RetrieveCar,
          component: () => import('../views/VipMaintain/RetrieveCar/RetrieveCar'),
          meta: {title: '找回车辆'}},
        {
          path: '/VipSuggest',
          name: 'VipSuggest',
          // component: VipSuggest,
          component: () => import('../views/VipMaintain/VipSuggest/VipSuggest'),
          meta: {title: '会员建议'}
        },
        //车辆管理
        { path: '/CarInfo',
          // component: CarInfo,
          component: () => import('../views/CarManage/CarInfo/CarInfo'),
          name: 'CarInfo',
          meta: {title: '车辆信息'}},
        { path: '/CarAuthentication',
          // component: CarAuthentication,
          component: () => import('../views/CarManage/CarAuthentication/CarAuthentication'),
          name: 'CarAuthentication',
          meta: {title: '车辆认证'}},
        { path: '/AuthenticationHistory',
          // component: AuthenticationHistory,
          component: () => import('../views/CarManage/AuthenticationHistory/AuthenticationHistory'),
          name: 'AuthenticationHistory',
          meta: {title: '车辆认证历史'}},
        //资源维护
        { path: '/RoadInParkingLot',
          name: 'RoadInParkingLot',
          // component: RoadInParkingLot,
          component: () => import('../views/Resources/RoadInParkingLot/RoadInParkingLot'),
          meta: { title: '路内停车场'}},
        { path: '/RoadInParkingSpace',
          name: 'RoadInParkingSpace',
          // component: RoadInParkingSpace,
          component: () => import('../views/Resources/RoadInParkingSpace/RoadInParkingSpace'),
          meta: {title: '路内泊位'}},
        { path: '/ParkingEquipment',
          name: 'ParkingEquipment',
          // component: ParkingEquipment,
          component: () => import('../views/Resources/ParkingEquipment/ParkingEquipment'),
          meta: {title: '车位设备'}},
        { path: '/HandheldTerminal',
          name: 'HandheldTerminal',
          // component: HandheldTerminal,
          component: () => import('../views/Resources/HandheldTerminal/HandheldTerminal'),
          meta: {title: '手持终端'}},
        //基础设置
        { path: '/Operate',
          name: 'Operate',
          // component: Operate,
          component: () => import('../views/BasisSet/Operate/Operate'),
          meta: {title: '运营公司'}},
        { path: '/RoleManage',
          name: 'RoleManage',
          // component: RoleManage,
          component: () => import('../views/BasisSet/RoleManage/RoleManage'),
          meta: {title: '角色管理'}},
        { path: '/BackUser',
          name: 'BackUser',
          // component: BackUser,
          component: () => import('../views/BasisSet/BackUser/BackUser'),
          meta: {title: '后台用户'}},
        { path: '/MenuManage',
          name: 'MenuManage',
          // component: MenuManage,
          component: () => import('../views/BasisSet/MenuManage/MenuManage'),
          meta: {title: '菜单管理'}},
        { path: '/Region',
          name: 'Region',
          // component: Region,
          component: () => import('../views/BasisSet/Region/Region'),
          meta: {title: '区域管理'}},
        { path: '/RoadManage',
          name: 'RoadManage',
          // component: RoadManage,
          component: () => import('../views/BasisSet/RoadManage/RoadManage'),
          meta: {title: '道路管理'}},
        { path: '/Holiday',
          name: 'Holiday',
          // component: Holiday,
          component: () => import('../views/BasisSet/Holiday/Holiday'),
          meta: { title: '节假日配置'}},
        //参数设置
        { path: '/DictionaryManage',
          name: 'DictionaryManage',
          // component: DictionaryManage,
          component: () => import('../views/BasisSet/ParameterSetting/DictionaryManage/DictionaryManage'),
          meta: { title: '字典管理'}},
        { path: '/BusinessParameter',
          name: 'BusinessParameter',
          // component: BusinessParameter,
          component: () => import('../views/BasisSet/ParameterSetting/BusinessParameter/BusinessParameter'),
          meta: { title: '业务参数'}},
        //系统运维
        { path: '/Shop',
          name: 'Shop',
          // component: Shop,
          component: () => import('../views/System/Shop/Shop'),
          meta: { title: '商户管理'}},
        { path: '/ParkingData',
          name: 'ParkingData',
          // component: ParkingData,
          component: () => import('../views/System/ParkingData/ParkingData'),
          meta: {title: '停车数据记录'},},
        { path: '/PaymentRecord',
          name: 'PaymentRecord',
          // component: PaymentRecord,
          component: () => import('../views/System/PaymentRecord/PaymentRecord'),
          meta: {title: '支付记录'},},
      ]
    }
  ]
})


